task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1 # your dataset classes
remap_mscoco_category: Trued

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    ann_file: /data2/detection_datasets/processed/synbase_coco/instances_train.json
    img_folder: /data2/detection_datasets/processed/synbase_yolov5/images/train
    return_masks: False
    transforms:
      type: Compose
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    ann_file: /data2/detection_datasets/processed/synbase_coco/instances_val.json
    img_folder: /data2/detection_datasets/processed/synbase_yolov5/images/val
    return_masks: False
    transforms:
      type: Compose
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
